### PR TITLE
Use redux in react component

### PR DESCRIPTION
**Pull request by Ghilain**
Requesting project review on bookstore app

### Project requirements
- First of all - make sure that you keep state immutable in reducers!
- Secondly, change the default state in your books reducer from an empty array to an array with a few books. One of the goals is to display them in your React components.
- Import Redux `Provider` and your store in the main component of your React app.
- Connect your app to the Redux store.
- Make sure that list of books displays books from Redux store.
    - Use `useSelector` to consume the state.
- In your React component responsible for adding new books, add functionality for "Add new" button click:
     - Import Redux `useDispatch`.
     - Set the data inputs in the local React state (set *title* and *author*  - NOTE: *categories* and *comments* are NOT part of this step). 
     - Once your new book object is ready to be submitted to Redux store, dispatch a corresponding action (import Action Creator that you created before and use it here).
- In your React component responsible for removing books, add a functionality for "Remove" button click:
    - Import Redux `useDispatch`.
    - Dispatch a corresponding action (import Action Creator that you created before and use it here).
- In your React component responsible for categories, add a functionality for "Check status" button click:
    - Import Redux `useDispatch`.
    - Dispatch a corresponding action (import Action Creator that you created before and use it here).

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @Ghilain, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Professional readme
✔️ Good PR description and title
✔️ Great job so far

## Required 
- [x] Kindly make sure to display `Under Construction` when the Check status button is clicked.

https://user-images.githubusercontent.com/70269507/174013253-2469b129-d6f2-4dc0-8fdf-0e36f284d593.mov



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ghilain** [comment]
Thank you @sja-thedude

**Review by AmaduKamara — COMMENTED** [review]
# Status: Approved 🟢🟢🟢 

Hi @Ghilain,

Good job working on the changes asked by the previous reviewer 👍 Keep rocking 

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights
✅ Correct use of Gitflow
✅ No linter error

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by AmaduKamara** [comment]
Hey, your project is approved. I mistakenly used the Github Comment option instead of Approved. Please go ahead, merge and submit it on your dashboard. 👍

**Comment by Ghilain** [comment]
Okay no problem @AmaduKamara and thank you

**Pull request merged**
